# pcp-on-web Project website

pcp-on-web:
  build: ./app-git/
  restart: always
  expose:
    - 80
  environment:
    - GITREPO=https://github.com/pcp-on-web/project-website.git
    - BASEDIR=html
  volumes:
   - ./data/pcp-on-web/www:/var/www/

# Kanboard database and app

kanboard-db:
  image: mariadb
  restart: always
  volumes:
    - ./data/kanboard-db/var-lib-mysql:/var/lib/mysql:rw
    - ./data/kanboard-db/etc-mysql:/etc-mysql:rw
  environment:
    - MYSQL_USER=kanboard
    - MYSQL_PASSWORD=password-1
    - MYSQL_DATABASE=kanboard
    - MYSQL_ROOT_PASSWORD=password-2

kanboard:
  build: ./app-kanboard/
  restart: always
  expose:
    - 80
  environment:
    - MYSQL_USER=kanboard
    - MYSQL_PASSWORD=password-1
    - MYSQL_DATABASE=kanboard
    - MYSQL_LINK=kanboard-db

  volumes:
    - ./data/kanboard/www:/var/www/
    - ./data/kanboard/data:/data
  links:
    - kanboard-db

# Nextcloud database and app
# to access nextcloud in subdirectory please call
# sudo ln -s . nextcloud
# change htaccess.RewriteBase to /nextcloud/ in config/apache-pretty-urls.config.php and config/config.php


nextcloud-db:
  image: mariadb
  restart: always
  volumes:
    - ./data/nextcloud-db/var-lib-mysql:/var/lib/mysql:rw
    - ./data/nextcloud-db/etc-mysql:/etc-mysql:rw
  environment:
    - MYSQL_USER=nextcloud
    - MYSQL_PASSWORD=password-3
    - MYSQL_DATABASE=nextcloud
    - MYSQL_ROOT_PASSWORD=password-4

nextcloud:
  image: nextcloud
  restart: always
  expose:
    - 80

  volumes:
      - ./data/nextcloud/www:/var/www/html/
  links:
    - nextcloud-db


research-community:
  build: ./app-wordpress/
  restart: always
  expose:
    - 80
  volumes:
    - ./data/research-community/:/var/www/html/

  environment:
    - BASEDIR=research-community
    - WORDPRESS_DB_HOST=research-community-db
    - WORDPRESS_DB_USER=wordpress
    - WORDPRESS_DB_PASSWORD=password-5
    - WORDPRESS_DB_NAME=wordpress
  links:
    - research-community-db

research-community-db:
  image: mariadb
  restart: always
  volumes:
    - ./data/research-community-db/var-lib-mysql:/var/lib/mysql:rw
    - ./data/research-community-db/etc-mysql:/etc-mysql:rw
  environment:
    - MYSQL_USER=wordpress
    - MYSQL_PASSWORD=password-5
    - MYSQL_DATABASE=wordpress
    - MYSQL_ROOT_PASSWORD=password-6



# http proxy 

proxy:
  image: nginx
  restart: always
  ports:
    - 80:80
    - 443:443
  restart: always
  mem_limit: 500MB
  volumes:
#    - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf:rw
    - ./data/nginx/ssl/:/etc/nginx/ssl/:rw
    - ./data/nginx/conf.d/:/etc/nginx/conf.d/:rw
#    - ./data/nginx/log/:/var/log/nginx/:rw
  links:
    - pcp-on-web
    - kanboard
    - nextcloud
    - research-community

